### ISSUE TITLE
Query parameters not optional for Connection::column

### ISSUE THREAD

**Issue by fkirkholt** [opis/database#10]
Second argument for `Connection::column` is now mandatory.

I would also request a method `ResultSet::column` with result of `PDOStatement::fetchColumn`.

**Comment by msarca** [comment]
The second argument of the `Connection::column` method is now optional([v3.0.1](https://github.com/opis/database/releases/tag/3.0.1)). The `ResultSet::column` method will be added in the next minor release.

**Comment by msarca** [comment]
The `ResultSet::column` method was added. See [v3.1.0](https://github.com/opis/database/releases/tag/3.1.0) release.
