### ISSUE TITLE
Syntax error in Model class.

### ISSUE THREAD

**Issue by Neppord** [opis/database#11]
On line [218] (https://github.com/opis/database/blob/master/lib/Model.php#L218) the method `getConnection` is declared both abstract and static. This seams to be not valid php, when I run the code it raises a error.

Hope you can find time to fix this issue, and write some tests. Alot of the code looks pretty good.

**Comment by sorinsarca** [comment]
A quick workaround looks like this:

```php
interface IModel {
  static function getConnection();
}

abstract class Model implements IModel {
  // here you should remove: public static abstract function getConnection(); 
}
```

So, in PHP if you want to create an static abstract method you must use an interface.

**Comment by Neppord** [comment]
Or it could be concrete, but throw a Exception that tells the user that it needs to implement the method.

**Comment by msarca** [comment]
I didn't notice this earlier because my `php.ini` file has `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`. The best solution at this time is to make the `getConnection` method concrete, as it has been suggested.
