### ISSUE TITLE
Connection class becomes a singelton on the Model.

### ISSUE THREAD

**Issue by Neppord** [opis/database#12]
I have been playing around witht the code base trying not to use `getConnection` since its one of the few ugly parts of the API.

It seams as if almost all stages except the `Model` has a connection to use instead of using `$model::getConnection`. If you add a 'Connection' member and constructor argument to the `Model` then every thing falls in place, except for `Model::find(x)` and all other static methods that needs a connection.

However all these static methods are not needed, since the `Query` object is doing all the work any way, and creating it is supper simple. Could maybe `getConnection` only be used when you use the static function syntax?

I'm willing to make a PR.

**Comment by Neppord** [comment]
Why singletons are bad: https://youtu.be/-FRm3VPhseI

**Comment by msarca** [comment]
The [proposed implementation](http://www.opis.io/database/orm#introduction) of the `getConnection` method has nothing to do with the [singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern)(which refers to a totally different thing) and is more like a safety mechanism that prevents opening multiple connections to the database server. In a way, it's similar to the  [getSequence](https://github.com/opis/database/blob/master/lib/Model.php#L632) method.

**Comment by Neppord** [comment]
I firmly disagree that the proposed `getConnection` is not making the `Connection` a Singelton, on the Model object.

Sure there are a few things missing, like a private constructor. But since the proposed implementation makes that instance global it doesn't matter that the name of `getConnection` isn't called `getInstance` and that its a static method on the `Model` and not on `Connection`. Or would you also clame that this example would not make it a Singelton.

```php
class Connection
{
    private static $instance;
    public static getInstance()
    {
        return self::$instance;
    }
}
```

What you call it doesn't really matter, only helps when discussing things. It is global: and that is bad. It is even forced to be global which is worse.

**Comment by msarca** [comment]
Sorry for being so concise in my last post, but I was a little busy. I'll try to elaborate and hopefully we will finally agree that the `getConnection` is not such a "bad" and "ugly" method. 
What you have presented here is not an implementation of the singleton pattern, but an implementation of the get/set pattern.
```php
class Foo
{
    protected $instance;
    
    public function getInstance()
    {
        return $this->instance;
    }
    
    public function setInstance($value)
    {
        $this->instance = $value;
    }
}

class Bar
{
    protected static $instance;
    
    public static function getInstance()
    {
        return static::$instance;
    }
    
    public static function setInstance($value)
    {
        static::$instance = $value;
    }
}
```
In the above example the `Foo` class implements the get/set pattern **at instance level**, while the `Bar` class implements the same pattern **at class level**. 
For both classes, the `getInstance` method represents the **getter** and the `setInstance` method represents the **setter**. When the **setter** is missing we say that the property is **read-only**. 
As you can see, the `Opis\Database\Model` class implements a get/set pattern **at class level** and it only defines a **getter**, so the connection property will be **read-only**.

**Comment by Neppord** [comment]
As I said before it actually doesn't matter what you call the pattern. It is still global state, and are therefore bad.

Sure, some times global state is unavoidable, or it is immutable (a recursive constant) and it doesn't matter. But here it is even forced upon the user of the library. Since the library internally reaches out into the global state to fetch the connection when doing 'sub-queries'. And there for the user have no choice then to have a global connection.

**Comment by Neppord** [comment]
If i where unclear. Its not setters and getters that are the main issue but that the memmbers and methods are static, therefore global.

**Comment by msarca** [comment]
You were right from the beginning..  The `Model` class should receive a `Connection` argument and now it does. It is more testable this way since you can mock the connection object and avoid hitting a database when running unit tests.
