### ISSUE TITLE
onError, onSuccess in transaction

### ISSUE THREAD

**Issue by asmdk** [opis/database#22]
php 5.6.12

im use transaction with callback:

`->onError(function(PDOException $e, $transaction){
                //code write log
                throw new \PDOException($e->getMessage());
            })
            ->onSuccess(function($transaction){
                //code write log
            })`

both methods i have fatal error, for example:
`Fatal error: Call to undefined method Opis\Database\Transaction::successCallback()`

that will be corrected in \opis\database\lib\Transaction.php, method execute, we should replace 
`            if ($this->successCallback !== null) {
                $this->successCallback($this);
            }`
on
` if ($this->successCallback !== null) {
                call_user_func($this->successCallback, $this);
            }`          
got error callback the same...

**Comment by msarca** [comment]
Fixed in [v3.2.2](https://github.com/opis/database/releases/tag/3.2.2). Thanks for reporting.
