### ISSUE TITLE
how add table prefix

### ISSUE THREAD

**Issue by pcse7en** [opis/database#31]
hello.
how can add prefix into the first of all tables in opis?

**Comment by msarca** [comment]
Hello. The concept of "prefixed tables" is application specific and that's why is not part of Opis Database's features. The developers are fully responsible of providing the correct table name when using the library. 
A solution would be the usage of a helper function when specifying table names.
```php
function pfx_table($table)
{
    $prefix = read_the_prefix_from_somewhere();
    if($prefix === null){
        return $table;
    }
    return $prefix . '_' . $table;
}
// Usage..
$db->from(pfx_table('users'))
       ->select()
       ->all();
```
