### ISSUE TITLE
Convert Select results into JSON object

### ISSUE THREAD

**Issue by JefferyHus** [opis/database#32]
Hi,
I was writing an API and loved your library, the struggle is when I select data from DB like this:
```sql
Jobs::where('title')->like('%'.$args['job'].'%')->first();
```
The result is returned as an object and couldn't find any way to convert it into an array.

**Comment by msarca** [comment]
Hello. Yes, indeed, the result is an object, more precisely the result is an instance of `Jobs` class. To represent an instance of an active record as an array, you should declare a specialized method (let's name it `toArray`) inside the `Jobs` class. Something like this:
```php
class Jobjs extends BaseModel
{
    // Some code here

   /**
    * To array
   **/
   public function toArray()
   {
       return array(
            'title' => $this->title,
            'description' => $this->description,
            // other properties
       );
   }
    
}
```
Then you could use it like this:
```php
$job = Jobs::where('title')->like('%'.$args['job'].'%')->first();
if($job){
    print_r($job->toArray());
} else {
    echo "Job doesn't exist";
}
```
Hope this helps

**Comment by JefferyHus** [comment]
thanks for the help :+1:
