### ISSUE TITLE
PDO could not find driver

### ISSUE THREAD

**Issue by JefferyHus** [opis/database#34]
This issue is shown only when I have tried to execute two queries at the same time, using axios JavaScript HTTP library, I have made a call to two endpoints of my API, then this exception is thrown, but when I call one endpoint at once everything goes smoothly, tested on PHP 7.0.10 & 5.6.25. Does Opis use existing connections instead of creating new one?

**Comment by msarca** [comment]
Opis Database is used in some pretty busy APIs and some massive data harvesting tools, for which we are providing technical support and consultancy, but we have never encounter the problems you are describing here. Can you give us an example that is reproductible, or at least the exact exception that is thrown?

**Comment by JefferyHus** [comment]
PDOException “could not find driver”, this is the exception I get, what I do is calling two endpoints at the same time:
```javascript
var self = this;

axios.get('/api/v1/customer/get').then(function (response) {
	if ( response.data.error )
	{
		swal('Oops..', response.data.error, 'error');
	}
	else
	{
		self.totalCustomers = response.data.result.length;
	}
}).catch(function (error) {
	swal('Oops..', error.response.data.error, 'error');
});
// get the customer history
axios.get('/api/v1/history/get').then(function (response) {
	if ( response.data.error )
	{
		swal('Oops..', response.data.error, 'error');
	}
	else
	{
		self.history = response.data.result;
		self.totalHistory = response.data.result.length;
	}
}).catch(function (error) {
	swal('Oops..', error.response.data.error, 'error');
});
```
in this case one of the requests is throwing that PDOException, but when I timeout one of this requests to occur after the other one things go well.

in the PHP part:
```php
/**
 * Customer get action
 */
public function get($request, $response, $args)
{
	/**
	 * If the uuid is set then get a specific customer
	 */
	try
	{
		if ( !isset($args['uid']) )
		{
			$results = Customer::findAll();

			foreach ($results as $customer)
			{
				$this->res['result'][] = $customer->toArray();
			}
		}
		else
		{
			$this->res['result'] = Customer::find($args['uid'])->toArray();
		}
	}
	catch (\Exception $e)
	{
		$this->res['error']  = $e->getMessage();
		$this->res['status'] = 400;
		$this->res['errorCode'] = $e->getCode();
	}
	
	return $response->withJson($this->res)->withStatus($this->res['status']);
}
// each action is in a different controller
/**
 * History get action
 */
public function get($request, $response, $args)
{
	/**
	 * If the uuid is set then get a specific history
	 */
	try
	{
		if ( !isset($args['uid']) )
		{
			$results = History::findAll();

			foreach ($results as $history)
			{
				$this->res['result'][] = $history->toArray();
			}
		}
		else
		{
			$this->res['result'] = History::find($args['uid'])->toArray();
		}
	}
	catch (\Exception $e)
	{
		$this->res['error']  = $e->getMessage();
		$this->res['status'] = 400;
		$this->res['errorCode'] = $e->getCode();
	}
	
	return $response->withJson($this->res)->withStatus($this->res['status']);
}
```

**Comment by msarca** [comment]
This error is thrown when a PDO driver required in your DSN is missing. Does `Customers` and `History` extend the same class? Maybe your classes use different DSN strings and one of them have a typo.

**Comment by JefferyHus** [comment]
they use the same DSN, and they extends the same class, the fix I did is that I have set a timeout call function on the `History` request and they both works now. But I wonder why such Exception is thrown when there is a DSN.

**Comment by msarca** [comment]
Are you using a load balancer to distribute traffic? If so, maybe one of your servers is not properly configured. This would explain why serial requests succeed, while some parallel requests fail. I will let this thread open for a while, but this issue is clearly related to PDO or server configuration, not to Opis Database.

**Comment by JefferyHus** [comment]
Hi, I have investigated the issue, and found out that the issue remains in the `ENV` package which isn't loading values so there was an empty DSN going to the `Connection` class.

**Comment by JefferyHus** [comment]
Thanks for your help, and you can close it as resolved thanks.

**Comment by msarca** [comment]
Glad to hear that you've managed to fix it
