### ISSUE TITLE
SQL Functions as DATE(), UNIX_TIMESTAMP()...etc

### ISSUE THREAD

**Issue by JefferyHus** [opis/database#36]
Apparently I can't perform any kind of these operations:

```php
$db->from('table_name')
	->orderBy('UNIX_TIMESTAMP(date_time)', 'desc')
	->select('row')->first();
```

**Comment by msarca** [comment]
Passing your function to the `orderBy` method as a string won't work because the library is unable to distinguish between a column's name and function's name. This kind of operations can be performed by using an expression: 

```php
$db->from('table_name')
    ->orderBy(function($expr){
        $expr->{'UNIX_TIMESTAMP('}->column('date_time')->{')'};
    }, 'desc')
    ->select('row')
    ->first();
```

There was a small bug that prevented users to pass a closure as the first argument of the `orderBy` method, but it was fixed in v3.6.9.

**Comment by JefferyHus** [comment]
thanks

**Comment by mauroagr** [comment]
I am try to make a 'SUBSTR', in INNER JOIN but dont have sucess
```
$list = $db->from('postagem')
                            ->join('sigep_rastreios', function($join){
                                $join->on('sigep_rastreios.id_pedido', 'postagem.id_pedido');
                            })
                            ->join('frete_meio_envio', function($join){
                                $join->on(function($sub){
                                    $sub->{'SUBSTR('}->column('frete_meio_envio.id_servico')->{', 1,5)'};
                                }, 'postagem.tipo_servico');
                            })
                            ->where('postagem.data')->eq(date('20190121'))
                            ->orderBy('postagem.id', 'desc')
                            ->limit(100)
                            ->select()
                            ->all()
``` 
I am make some think wrong?

**Comment by msarca** [comment]
Yes, you are, but it has nothing to do with this library. That's not how JOIN works. The comparison should be made between two columns, not between a string and a column.

**Comment by mauroagr** [comment]
Then i can't compare two strings in join using opis?

**Comment by msarca** [comment]
You should try and invert the condition like bellow

```php
$join->on('postagem.tipo_servico', function($sub){
    $sub->{'SUBSTR('}->column('frete_meio_envio.id_servico')->{', 1,5)'};
});
```

**Comment by mauroagr** [comment]
I try, the function no run and return null in parameters.
i will change the DB.
Thanks for help
