### ISSUE TITLE
Composite primary keys in models

### ISSUE THREAD

**Issue by miklinux** [opis/database#37]
Hello,
How to handle composite primary keys for a table (multiple columns) in models? It seems there’s no way to specify an array as primary key.

**Comment by msarca** [comment]
Hey, sorry for the late response. Unfortunately, composite keys are not supported. 
We're are planning to move the ORM component into its own repository and migrate from active record pattern to data mapper pattern. The new library will have support for composite keys and it will be super easy to use. If you like, I could let this issue open and drop you a line when the new library is ready to be released.

**Comment by miklinux** [comment]
Sure, I’d like to be informed when the new library will be ready.
Do you have an ETA for the release?

Thanks

**Comment by msarca** [comment]
Somehow I've managed to miss this. If it still matters https://opis.io/orm
