### ISSUE TITLE
DISTINCT only one column

### ISSUE THREAD

**Issue by mauroagr** [opis/database#40]
Hi,
I dont find how i can do a DISTINCT('p.id') from one column.
using ->distinct(), they filter all columns, but i don't will.
Have a method to solve this?

**Comment by msarca** [comment]
The selected columns must be always specified using the `select` method. 
```php
$result = $db->from('users')
           ->distinct()
           ->select('id')
           ->all();

// multiple columns

$result = $db->from('users')
           ->distinct()
           ->select(['name', 'age'])
           ->all();
```

**Comment by msarca** [comment]
And how would that SQL query look like?

**Comment by mauroagr** [comment]
I was thinking wrong...i use group and solve the problems.
Thanks for help
