### ISSUE TITLE
How to modify the left-hand-side operator of where conditions

### ISSUE THREAD

**Issue by nepda** [opis/database#41]
I've something like this:

```
$group->orWhere('tbl.FIELD')->like($value);
```
and i need something like

```
$group->orWhere('LOWER(tbl.FIELD)')->like($value);
```

Is this possible with this library? An if so, how?

Please note: I'm not able to change the collation of the schema.

**Comment by sorinsarca** [comment]
A new version (which allows expressions on the left hand side of the operator) will be released in the next hours. I'll post an update and an example on how to use them (because the docs will be updated later).

**Comment by nepda** [comment]
This would be very nice. Thank you :)

**Comment by sorinsarca** [comment]
Version **4.1.0** is now released.

Now the `where`, `andWhere` and `orWhere` methods accept on the second parameter a boolean
indicating that the closure (first parameter) is an expression and not a group (default is `false` so it will be treated as a group to keep compatibility with previous versions).

So, for your case it should be something like:

```php
use Opis\Database\SQL\Expression;

$group
   ->orWhere(function (Expression $expr) {
    $expr->lcase('tbl.FIELD');
    // OR, if you need a specific function (like lower)
   // $expr->{'LOWER('}->column('tbl.FIELD')->{')'};
   }, true) // !!! Notice here that we pass true so our closure will handle an expression
   ->like($value);
```

The docs will be updated soon.
