### ISSUE TITLE
Schema support for Firebird

### ISSUE THREAD

**Issue by nepda** [opis/database#42]
Is there any plan to support Firebird for Schema?

Is it correct, that Implementing `\Opis\Database\Schema\Compiler\Firebird` should resolve this?

If there are no current plans for this. Is there anything you can tell me to watch for when implementing it by my own?

**Comment by sorinsarca** [comment]
> Is it correct, that Implementing \Opis\Database\Schema\Compiler\Firebird should resolve this?

Yes.

> If there are no current plans for this. Is there anything you can tell me to watch for when implementing it by my own?

Currently there are no plans, but if you want to create the Firebird schema compiler we accept PRs,
and after the unit tests are created we release a new version.
Well, I don't think there is something special to watch for, except for the `AUTO INCREMENT` fields.

Just let me know if you are interested in creating the Firebird schema compiler.

Thanks!
