### ISSUE TITLE
Select with inner join

### ISSUE THREAD

**Issue by mauroagr** [opis/database#45]
Dear, 
I have two tables that i make a inner join. But in the both tables have a column with field named 'title'.
My question is, i will use ->select(), without use alias name, like the select below
```
result = $db->from([getenv('DB_PREFIX').'kpi' => 'kpi'])
                        ->join([getenv('DB_PREFIX').'kpi_unit' => 'unit'], function($join){
                               $join->on('kpi.id_kpi_unit', 'unit.id_kpi_unit');
                            })
                        ->orderBy('id_kpi', 'ASC')
                        ->select()
                        ->all();
```
In this situation the result show only one 'title' field.
how i can solve this?
Thanks

**Comment by msarca** [comment]
Checkout the documentation for [fetching option](https://docs.opis.io/database/4.x/results-handling.html#fetching-options), especially the `fetchNamed` method. Another option would be to alias one of the `title` columns, like below
```php
$db->from('t')
       // join, order, etc.
       ->select(['*', 't.title' => 't_title'])
       ->all()
```

**Comment by mauroagr** [comment]
Many thanks.
If i will rename all fields from one table adding a prefixo in the names, can do?
thanks
Mauro

**Comment by msarca** [comment]
You could explicitly tell what fields to be selected and alias them. It would be much simpler.

```php
$result = $db->from([getenv('DB_PREFIX').'kpi' => 'kpi'])
    ->join([getenv('DB_PREFIX').'kpi_unit' => 'unit'], function($join){
        $join->on('kpi.id_kpi_unit', 'unit.id_kpi_unit');
    })
    ->orderBy('id_kpi', 'ASC')
    ->select([
        'kip.id' => 'id',
        'kip.title' => 'kip_title',
        'kip_unit.title' => 'kip_unit_title',
        // other fields
    ])
    ->all();

foreach ($result as $record) {
    echo $record->id, $record->kip_title, $record->kip_unit_title; 
}
```
