### ISSUE TITLE
FIREBIRD Select 

### ISSUE THREAD

**Issue by elvispdosreis** [opis/database#47]
I'm having trouble using firebird, the generated sql puts the table name and fields in double quotation marks

`SELECT * FROM "table"`

**Comment by msarca** [comment]
If you want to get rid of the double quoted identifiers just use the `setWrapperFormat` method on the connection object. Also, since in Firebird every identifier is uppercased by default, you might want to use `PDO::CASE_LOWER`.

```php
$connection = new Connection("firebird:...");
$connection
    ->setWrapperFormat('%s') // no double quotes
    ->option(PDO::ATTR_CASE, PDO::CASE_LOWER); // lower case
```

**Comment by elvispdosreis** [comment]
thanks
