### ISSUE TITLE
Cache count()

### ISSUE THREAD

**Issue by elvispdosreis** [opis/database#49]
When paging results, when I use count (), it fires sql for all queries I make during paging, it would be possible to implement a cache so that it returns count () from cache, we can mount a combination sql with the parameters, when this value is equal the cache can be used.

**Comment by sorinsarca** [comment]
> When paging results, when I use count (), it fires sql for all queries I make during paging,

Well, without a code example I cannot point you in the right direction. But I can say that this can probably be solved without any internal cache.

Sorry for the late response. Please reopen if needed.
