### ISSUE TITLE
Create table

### ISSUE THREAD

**Issue by silv3r4u** [opis/database#5]
How create table with opis database? Or how to run sample Query?

**Comment by msarca** [comment]
Opis Database has an integrated schema builder, but unfortunately it is not yet fully documented.
http://www.opis.io/database/schema.html#creating-tables

```php
$db->schema()->create('table_name', function($table){
    $table->integer('id')->autoincrement();
    $table->string('email')->notNull()->unique();
    $table->integer('age');
   //Other columns ..
});
```
Another option is to use the underlying [PDO](http://php.net/manual/en/book.pdo.php) object of the current database instance and to write and execute your SQL command yourself.

```php
$command = 'CREATE TABLE my_table ....'; //SQL command
$db->getConnection()->pdo()->exec($command); //execute SQL command
```

**Comment by silv3r4u** [comment]
Thanks!
