### ISSUE TITLE
Get Raw SQL from insert

### ISSUE THREAD

**Issue by mauroagr** [opis/database#53]
Hi,
I am have this insert
```
    $result = $db->insert($fieldsPrep)->into('pedidos_detalhes');
```
But i dont need that they run, only prepare the sql and then i get in varible and use after.
I dont find this options in opis, or how i can do this.
Thanks
Mauro

**Comment by GonistLelatel** [comment]
see example of using the offline `SchemaConnection`
https://github.com/GonistLelatel/opis_database/blob/master/example/insertSQL/echoInsert.php

```
<?php
require __DIR__ . '/../../vendor/autoload.php';

use Opis\Database\SchemaConnection;
use Opis\Database\Database;

$mysql = new SchemaConnection('mysql');
$db = new Database($mysql);

$db->insert(array(
	'name' => 'John Doe',
	'email' => 'john.doe@example.com'
))
->into('users');

echo $mysql->getSQL();
```
`INSERT INTO `users` (`name`, `email`) VALUES ('John Doe', 'john.doe@example.com')`

**Comment by mauroagr** [comment]
This solve my problem.
Thanks @GonistLelatel

**Comment by nguereza-tony** [comment]
Hello how to get this in the latest version of the library ?
