### ISSUE TITLE
Firebird Count And Order BY

### ISSUE THREAD

**Issue by elvispdosreis** [opis/database#56]
SQL in Fiberdird with error order by

count does not need order by it could be removed during SQL assembly

```
$size = $result->count();
```

```
<?php
 $result = $db->from('vw_escrituracao_fiscal');

 $itens = $result->limit($params->limit)
            ->offset($params->offset)
            ->orderBy('id', $params->order_by ?? 'asc')
            ->select()
            ->fetchClass(ListNFSE::class)
            ->all();
$size = $result->count();
```

**Comment by msarca** [comment]
A simple `$size = $db->from('vw_escrituracao_fiscal')->count();` will fixit for you.

Anyway, this is not a bug, the behaviour is correct. You should not reuse the same object instance for doing different SQL operations. Please refer to the PHP documentation regarding [objects  and references](https://www.php.net/manual/en/language.oop5.references.php).

**Comment by elvispdosreis** [comment]
I'm sorry but I disagree with creating another instance to count the records only.
This example I went through is simple, in a more complex situation, where I am using multiple where and inner joins this would make a code replication just for me to count the records to do a pagination.

```
<?php
 $result = $db->from('vw_escrituracao_fiscal');

 $result->where('date')->between('2019-11-10', '2019-11-17');

//various conditions where
$result->where ....
$result->where ...
$result->where ...
$result->where ...

 $itens = $result->limit($params->limit)
            ->offset($params->offset)
            ->orderBy('id', $params->order_by ?? 'asc')
            ->select()
            ->fetchClass(ListNFSE::class)
            ->all();
// $size = $result->count();
```
you suggest i do that

```
<?php
 $result = $db->from('vw_escrituracao_fiscal');

 $result->where('date')->between('2019-11-10', '2019-11-17');

various conditions where
$result->where ....
$result->where ...
$result->where ...
$result->where ...

$size = $result->count();
```

**Comment by msarca** [comment]
You are not required to replicate your code, but you must use a different object instance for each operation. Something like bellow:

```php
// Filter
$query = $db->from('my_database')
            ->where('column_a')->is($someValue)
            ->where('column_b')->is($otherValue);

// obtain new object instance
$counter = clone $query;

// Sort, paginate and fetch
$results = $query->limit($limit)
                ->offset($offset)
                ->orderBy('column_c')
                ->select()
                ->all();

// Count
$count = $counter->count();
```

Of course, it is not necessary to store the cloned instance into a variable. You could use it directly

```php
// obtain new object instance & count
$count = (clone $query)->count();
```

**Comment by elvispdosreis** [comment]
thanks
