### ISSUE TITLE
How to write a conditional query

### ISSUE THREAD

**Issue by zeydo** [opis/database#57]
`get($data = [])
    {
        $query = $db->from('table');
        if ($data["search"]) {
            $query->where('column')->like($data["search"].'%');
        }
        $query->select();
        return $query->all();
    }`

Or ;

`function get($data = [])
    {
         $db->from('table');
        if ($data["search"]) {
            $db->where('column')->like($data["search"].'%');
        }
        $db->select();
        return $db->all();
    }`

How do I make them work?

**Comment by msarca** [comment]
```php
$query = $db->from('foo');

if ($data['search']) {
    // store the object returned by the "where" method
    $query = $query->where('column')->like($data['search']);
}
// Please refer to the documentation
// https://docs.opis.io/database/4.x/results-handling.html
$result = $query->select();

// do something with $result
return $result->all();
```
