### ISSUE TITLE
SQLite—Schema::getCurrentDatabase() fails

### ISSUE THREAD

**Issue by barryhughes** [opis/database#58]
`Opis\Database\Schema\Compiler\SQLite::currentDatabase()` is declared to return an array but returns a string, causing breakages.

This can be demonstrated with the following code:

```php
use Opis\Database\Connection;
use Opis\Database\Database;

$database = new Database(new Connection('sqlite:/tmp/test.db'));
$database->schema()->hasTable('foo');
```

Relevant error:

```
PHP Fatal error:  Uncaught TypeError: Return value of Opis\Database\Schema\Compiler\SQLite::currentDatabase() must be of the type array, string returned in /project-path/vendor/opis/database/src/Schema/Compiler/SQLite.php:117
```

The Oracle, Postrge and SQL Server implementations all return an array so are not impacted, this is only an issue for SQLite. Relevant source:

* [Compiler::currentDatabase()](https://github.com/opis/database/blob/4.0.0/src/Schema/Compiler.php#L586)
* [SQLite::currentDatabase()](https://github.com/opis/database/blob/4.0.0/src/Schema/Compiler/SQLite.php#L115-L118)

**Comment by msarca** [comment]
Fixed in v4.1.1. Thanks.
