### ISSUE TITLE
Crash with opis

### ISSUE THREAD

**Issue by Aknotsdeath** [opis/database#6]
I have been getting this crash with opis installed and I have not been able to figure out what causes it. http://pastebin.com/bKJ1Es3v

**Comment by Aknotsdeath** [comment]
Also I am playing a mod pack I have made.

**Comment by msarca** [comment]
Hello. I believe that there is a naming confusion. Opis Database is a PHP database abstraction layer, not a Java library. Moreover, the entire Opis project is focused around PHP programming language and it doesn't have (at this point) nothing to do with Java. 
Maybe you should try out this google search https://www.google.com/search?q=mcp.mobius.opis
