### ISSUE TITLE
is there a way to select group_concat with select(...) or i must use raw sql somehow?

### ISSUE THREAD

**Issue by SerjoA** [opis/database#63]
thanks for the great package btw

**Comment by msarca** [comment]
You could make a custom [field selection](https://docs.opis.io/database/4.x/fields-selection.html) and pass an [expression](https://docs.opis.io/database/4.x/expressions.html) to the `column` method.

```php
$result = $db->from('users')
             ->select(function($include){
                $include->column(function ($expr) {
                    $expr->{'group_concat(col)'};
                });
             })
             ->all();
```

**Comment by SerjoA** [comment]
i will try that , thank you
