### ISSUE TITLE
How to connect sqlsrv?

### ISSUE THREAD

**Issue by zeydo** [opis/database#67]
`$connection = new Connection(
		    'sqlsrv:server=myserver;database=mydatabase,
		    'user,
		    'password'
		);

		$db = new Database($connection);
		$result = $db->from('mytable')
             ->select()
             ->all();`
SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object.
`
$MSSQL = new \PDO('sqlsrv:Server=myserver;Database=mydatabase,'user','mytable');
$MSSQL->exec("SET NAMES 'UTF-8'");
$rs = $MSSQL->prepare("SELECT * FROM mytable");

	$rs->execute();
	$results =  $rs->fetchAll(\PDO::FETCH_ASSOC);`
This connection successful

**Comment by msarca** [comment]
Please review [the documentation](https://www.php.net/manual/ro/ref.pdo-sqlsrv.connection.php) for MS SQL DSN. There is a `Server`, not a `server` and a `Database`, not a `database`.
