### ISSUE TITLE
orderby rand() Implemented

### ISSUE THREAD

**Issue by rw1digital** [opis/database#68]
hello, I would like to share a new ORDERBY method for RAND () to update your repository.

version 4.1

I needed to use the ORDERBY rand () method but I see that it was not possible because it is attributed to the query columns.

so I created a new "orderByRaw" method so that it is possible to write as needed for each query.

//--------------------------------------------------------------------------------------------------------------------------------------------
file: Query.php
namespace: Opis \ Database \ SQL
line 132
new method
/**
     * @param   string
     * @param   string $order (optional)          
     * @return  Select|SelectStatement
     */
	public function orderByRaw($order=null)
    {
        return $this->buildSelect()->orderByRaw($order);
    }

//--------------------------------------------------------------------------------------------------------------------------------------------

file: SelectStatement.php
namespace: Opis\Database\SQL
line: 137
new method
/**
     * @param |string|optional
     * @param string $order     
     * @return SelectStatement
     */
    public function orderByRaw($order=null): self
    {
        $this->sql->addOrderRaw($order);
        return $this;
    }

//--------------------------------------------------------------------------------------------------------------------------------------------

file: Compiler.php
namespace: Opis\Database\SQL; 
line: 51 
$sql .= $this->handleOrderingRaw($select->getOrderRaw());

//--------------------------------------------------------------------------------------------------------------------------------------------

file: SQLStatement.php
namespace: Opis\Database\SQL;

###line: 30

protected $orderRaw;

###line: 348
/**     
     * @param string $orderraw
     */
    public function addOrderRaw(string $orderRaw)
    {     
	   return $this->orderRaw=$orderRaw;
    }

###line: 486
 /**
     * @return string
     */
   public function getOrderRaw()
    {
        return $this->orderRaw;
    }

//--------------------------------------------------------------------------------------------------------------------------------------------

how to use

$result = $db->from('users')
             ->orderByRaw('rand()')
             ->select()
             ->all();

**Comment by msarca** [comment]
You should use [Expressions](https://docs.opis.io/database/4.x/expressions.html). 

```php
$result = $db->from('users')
            ->orderBy(function($expr){
               $expr->op('rand()');
            })
            ->select()
            ->all();
```

**Comment by deba12** [comment]
@msarca please add this example in documentation.

Thanks
