### ISSUE TITLE
Firebird compiler wrapper

### ISSUE THREAD

**Issue by marxxx** [opis/database#7]
There is error while using Firebird 1.5 because of compiler wrapper.

I fixed it by adding this wrapper:
protected $wrapper = '%s';
to vendor/opis/database/lib/Compiler/Firebird.php

**Comment by msarca** [comment]
This is because the quoted identifiers are case-sensitive in Firebird. Starting from version 3.0.0, you can specify a custom wrapper by using the `setWrapperFormat` method.
```php
$connection = Connection::create(...)
                        ->setWrapperFormat('%s');
Database $db = new Database($connection);
```
