### ISSUE TITLE
Is there an upsert method available?

### ISSUE THREAD

**Issue by mcasto** [opis/database#70]
Right now, I did this:

```
      try {  // insert
        $db->insert($item)->into($table);
      } catch (Exception $e) {
        if ($e->getCode() == 23000) {
          $db->update($table)->where('_id')->is($item['_id'])->set($item);
        }
      }
```

and that works, but I'm curious about two things:
* if this is the best way and 
* if I've actually overlooked a predefined function for this?

**Comment by sorinsarca** [comment]
> if I've actually overlooked a predefined function for this?

There is no upsert method available.

> if this is the best way

I would also use a [transaction](https://docs.opis.io/database/4.x/transactions.html) as wrapper for your code

**Comment by mcasto** [comment]
Thanks for the sanity check :D
