### ISSUE TITLE
How to catch errorInfo PDO?

### ISSUE THREAD

**Issue by rw1digital** [opis/database#73]
Currently, I can only catch the getCode () method when an exception occurs.

Exception:
SQLSTATE [23000]: Integrity constraint violation: 1062 Duplicate entry '1-7898480930336' for key 'pro_emp_id, pro_codigo'
$ex->getCode()  --> only returns the standard error 23000

I need to catch the database error in case "1062"

my query example.

```try
		{	
			parent::db()->insert($dataSave)->into(self::tb());			
			return [200];
		}		
		catch(\PDOException $ex)
		{
			return [400,$ex->getMessage(),$ex->getCode(),$ex];
		}	
```

**Comment by msarca** [comment]
This is not related to our library. https://www.php.net/manual/en/class.pdoexception.php
