### ISSUE TITLE
Get unique value after insert and filter where by string

### ISSUE THREAD

**Issue by veerkun** [opis/database#74]
Question 1: how to get unique auto increment ID column value after run insert success?
Question 2:  (SOLVED) How to add where from string
I want filter where by :  $where_str = "ID%3=1 AND email NOT NULL";
Raw sql: Select * from user where ID%3=1 AND email NOT NULL
Please help me build this in ->where
Thank you
....
Update: I had solved question 2 with bellow code:
`$where_str = "ID%3=1 AND email NOT NULL";`
`$result = $db->from('users')
             ->where(function($expr) use ($where_str ){
                    $expr->op($where_str );
                }, true)->nop();`

**Comment by sorinsarca** [comment]
1.
```php
$db->getConnection()->getPDO()->lastInsertId();
```

2.

```php
$db->from('users')
      ->where(fn ($e) => $e->column('id')->op('%')->value(3), true)->is(1)
      ->andWhere('email')->notNull()
      ->select()
      ->all();
```

**Comment by veerkun** [comment]
thanks so much
