### ISSUE TITLE
How to get raw before sql limit function?

### ISSUE THREAD

**Issue by zeydduran** [opis/database#77]
Hi,

I am trying to paginate with datatable. But I need the total number of rows in the table for the datatable plugin to work properly.
The raw sql statement looks like this;

`<?php 
      $sql = 'SELECT * FROM table';
        if ($_POST["search_or_filter_data"]) {
            $sql .= 'where column = '. $_POST["search_or_filter_data"];
        }
        $count = 'SELECT COUNT(*) as total FROM ('.$sql.') count_row_table'; // What is required of me
        $sql .= ' LIMIT '.$_POST["limit"].' OFFSET '.$_POST["offset"];
?>`
Is it possible to do the above example with Opis?

I hope I could explain. Thank you

**Comment by sorinsarca** [comment]
You don't need raw sql. Use opis query builder:

```php
$query = $db->from('users')
            ->where('age')->is(18) // add your filters
;

// get total count 
// (you need to clone the query to prevent it from being altered - that's why the clone keyword is used)
$total = (clone $query)->count();

$results = $query
            ->limit(25)->offset(10) // apply offset and limit
            ->all(); // get result
```
