### ISSUE TITLE
Feature request: possibility to use some complicated expression in select statement

### ISSUE THREAD

**Issue by nguereza-tony** [opis/database#79]
Hello thank for this great tools.
After reading the documentation and navigate inside the codes I don't see anything related to how use complicated expression in select statement.
Example how to build this query:
`SELECT CAST(DATEDIFF (NOW(), created_at) AS INTEGER) AS nb_day FROM my_table;`

Thanks you

**Comment by msarca** [comment]
Hi! The feature already exists but it seems that we forgot to provide documentation. What you are describing can be easily achieved by using [custom field selection](https://opis.io/database/4.x/fields-selection.html#adding-columns) and [expressions](https://opis.io/database/4.x/expressions.html). It will look something like bellow

```php
$result = $db->from('my_table')
    ->select(function($include){
        $include->column(function($expr) {
            $expr->op('CAST(DATEDIFF (NOW(), ')->column('created_at')->op(') AS INTEGER)');
        }, 'nb_day');
    })
    ->all();
```

If you are planning to reuse this, we could further optimize it

```php
function dateDiff(string $column): callable {
    return function ($expr) use ($column) {
        $expr->op('CAST(DATEDIFF (NOW(), ')->column($column)->op(') AS INTEGER)');
    };
}
```

Now we can use our newly created function to write more compact and readable code

```php
$result = $db->from('my_table')
    ->select(function($include){
        $include->column(dateDiff('created_at'), 'nb_day');
    })
    ->all();
```

**Comment by nguereza-tony** [comment]
Thanks you I understand
