### ISSUE TITLE
Multiple conditions if empty records come

### ISSUE THREAD

**Issue by marquesjuniorpalmas** [opis/database#82]
if($a != ''){
$sql_a = "AND a = '".$a."'";
}else{
$sql_a = "";
}

if($b != ''){
$sql_b = "AND b = '".$b."'";
}else{
$sql_b = "";
}

if($c != ''){
$sql_c = "AND c = '".$c."'";
}else{
$sql_c = "";
}

$sql = " ".$sql_a." ".$sql_b." ".$sql_c." ";

**Comment by sorinsarca** [comment]
This isn't related to opis/database.

**Comment by marquesjuniorpalmas** [comment]
how could you use this instruction within opis?

**Comment by msarca** [comment]
Here is an example of how to write a conditional query https://github.com/opis/database/issues/57

**Comment by sorinsarca** [comment]
And here is the link to docs https://opis.io/database/4.x/
