### ISSUE TITLE
Transactions with rollback

### ISSUE THREAD

**Issue by mauroagr** [opis/database#83]
Dear,
I have a class Itens and other that save the stock movement.
But i need use commit/rollback if somethink be wrong.
Class Itens
```
$result = $db->insert((array)$data)
                      ->into(getenv('DB_PREFIX').'erp_pedido_itens');
```
Class Stock
```
$result = $db->insert((array)$data)
                      ->into(getenv('DB_PREFIX').'erp_estoque_mvt');
```

The both are started by a controller, but i dont find the best way to rollback when some of them get a excetion.
Any idea or more complex examples from transactions to try.
Thanks

**Comment by msarca** [comment]
Here is the documentation for [transactions](https://opis.io/database/4.x/transactions.html). The transactions are committed and rolled back automatically. If you want to manually control transactions, then you will need to obtain the underlying PDO object from a connection and write your own logic.

```php
$pdo = $connection->getPDO();
```
