### ISSUE TITLE
Support for NULLS FIRST/LAST for all databases

### ISSUE THREAD

**Issue by fkirkholt** [opis/database#9]
For Oracle I can write:
```
$db->from('users')
   ->orderBy('age', 'NULLS LAST')
   ->select()
   ->all()
```
But this doesn't work in MySQL for instance.

**Comment by msarca** [comment]
Hi. Thanks for reporting this issue. This should be fixed in  [3.0.0](https://github.com/opis/database/releases/tag/3.0.0). Take a look at the [documentation](http://www.opis.io/database/order.html#ordering-null-values) for syntax.
