### ISSUE TITLE
Package maintenance?

### ISSUE THREAD

**Issue by 8ctopus** [opis/database#99]
Hello!

I'm considering using your package, however looking at the last release and compatibility issues with the latest versions of php, I'm in doubt.

Could you please let me know about the package maintenance status?

**Comment by CasperHK** [comment]
It seems like no active maintenance for this project. If you are creating new project with PHP, I think it is better to use latest version of Laravel or Doctrine.

**Comment by 8ctopus** [comment]
Yes, you are right, but it's sad because it's a great project.

**Comment by sorinsarca** [comment]
I will review all PRs and release a new version by the end of this week.

**Comment by 8ctopus** [comment]
@sorinsarca I have made some work on a dev branch in my fork, maybe you will find some useful commits that you can merge.

**Comment by sorinsarca** [comment]
v4.3 is now compatible with php8
